---
- name: Update and upgrade Ubuntu hosts
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist

