---
- name: Generate SSH key pair if not present and display public key
  hosts: all
  become: no
  gather_facts: yes
  tasks:
    - name: Check if id_ed25519.pub file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
      register: pub_key_stat

    - name: Generate SSH key pair (ed25519)
      ansible.builtin.command:
        cmd: ssh-keygen -t ed25519 -N "" -f "{{ ansible_env.HOME }}/.ssh/id_ed25519"
      when: not pub_key_stat.stat.exists

    - name: Ensure .ssh directory has correct permissions
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"
      when: not pub_key_stat.stat.exists

    - name: Read id_ed25519.pub contents
      ansible.builtin.slurp:
        src: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
      register: pub_key_contents

    - name: Display id_ed25519.pub contents
      ansible.builtin.debug:
        msg: "Public Key ({{ inventory_hostname }}): {{ pub_key_contents.content | b64decode }}"
