---
- name: Install CUDA 11.8 and set it as default
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  tasks:
    - name: Download NVIDIA CUDA Keyring
      ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        dest: /tmp/cuda-keyring_1.0-1_all.deb
        mode: '0644'

    - name: Install NVIDIA CUDA Keyring
      ansible.builtin.apt:
        deb: /tmp/cuda-keyring_1.0-1_all.deb
        state: present
      notify:
        - Remove CUDA Keyring DEB

    - name: Install CUDA and CUDA 11.8
      ansible.builtin.apt:
        name:
          - cuda
          - cuda-11-8
        update_cache: yes
      register: cuda_install

    - name: Set default CUDA version to 11.8
      ansible.builtin.command:
        cmd: update-alternatives --set cuda /usr/local/cuda-11.8
      args:
        warn: no

    - name: Reboot server if CUDA was installed
      ansible.builtin.reboot:
      when: cuda_install.changed

    - name: Wait for the servers to come back online
      wait_for_connection:

    - name: Run nvidia-smi
      ansible.builtin.command:
        cmd: nvidia-smi
      register: nvidia_smi_output

    - name: Display NVIDIA Driver Version
      ansible.builtin.debug:
        msg: "NVIDIA Driver Version on {{ inventory_hostname }}: {{ nvidia_smi_output.stdout_lines[2].split('|')[1].strip() }}"

  handlers:
    - name: Remove CUDA Keyring DEB
      ansible.builtin.file:
        path: /tmp/cuda-keyring_1.0-1_all.deb
        state: absent

