---
- name: Install CUDA 11.8 and set it as default
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  tasks:
    - name: Download NVIDIA CUDA Keyring
      ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        dest: /tmp/cuda-keyring_1.0-1_all.deb
        mode: '0644'

    - name: Install NVIDIA CUDA Keyring
      ansible.builtin.apt:
        deb: /tmp/cuda-keyring_1.0-1_all.deb
        state: present
      notify:
        - Remove CUDA Keyring DEB

    - name: Install CUDA and CUDA 11.8
      ansible.builtin.apt:
        name:
          - cuda
          - cuda-11-8
        update_cache: yes

    - name: Set default CUDA version to 11.8
      ansible.builtin.command:
        cmd: update-alternatives --set cuda /usr/local/cuda-11.8
      args:
        warn: no

  handlers:
    - name: Remove CUDA Keyring DEB
      ansible.builtin.file:
        path: /tmp/cuda-keyring_1.0-1_all.deb
        state: absent

