---
- name: Install useful tools
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  vars:
    conda_env_name: base
  tasks:
    - name: Install gpustat in the Conda environment e.g. gpustat -cp --watch
      become: no
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'HOME') }}/miniconda3/bin/conda install -y -c conda-forge -n {{ conda_env_name }} gpustat"

    - name: Install tree
      ansible.builtin.apt:
        name: tree
        state: present

    - name: Install rg - like grep but better
      ansible.builtin.apt:
        name: ripgrep
        state: present

    - name: Install tldr - like man but better
      ansible.builtin.apt:
        name: tldr
        state: present

    - name: Install exa - like ls but better
      ansible.builtin.apt:
        name: exa
        state: present

    - name: Install ncdu
      ansible.builtin.apt:
        name: ncdu
        state: present

    - name: Install duf - like df but better
      ansible.builtin.apt:
        name: duf
        state: present

    - name: Install jq
      ansible.builtin.apt:
        name: jq
        state: present

    - name: Install speedtest-cli
      ansible.builtin.apt:
        name: speedtest-cli
        state: present

    - name: Install iotop
      ansible.builtin.apt:
        name: iotop
        state: present
