---
- name: Install useful tools
  hosts: all
  become: yes
  vars_files:
    - sudo.yml
  vars:
    conda_env_name: base
  tasks:
    - name: Install gpustat in the base Conda environment e.g. gpustat -cp --watch
      become: no
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'HOME') }}/mambaforge/bin/conda install -y -c conda-forge -n {{ conda_env_name }} gpustat"

    - name: Remove existing watch_df.sh script
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/watch_df.sh"
        state: absent

    - name: Create watch_df.sh script
      become: no
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          watch df -lh --output=target,avail
        dest: "{{ lookup('env', 'HOME') }}/watch_df.sh"
        mode: '0755'

    - name: Remove existing nvidia_power_limit.sh script
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/nvidia_power_limit.sh"
        state: absent

    - name: Create nvidia_power_limit.sh script
      become: no
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          sudo nvidia-smi -pm ENABLED
          sudo nvidia-smi -pl 300
        dest: "{{ lookup('env', 'HOME') }}/nvidia_power_limit.sh"
        mode: '0755'

    - name: Remove existing watch_gpu.sh script
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/watch_gpu.sh"
        state: absent

    - name: Create watch_gpu.sh script
      become: no
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          gpustat -cp --watch 2
        dest: "{{ lookup('env', 'HOME') }}/watch_gpu.sh"
        mode: '0755'

    - name: Install tree
      ansible.builtin.apt:
        name: tree
        state: present

    - name: Install rg - like grep but better
      ansible.builtin.apt:
        name: ripgrep
        state: present

    - name: Install tldr - like man but better
      ansible.builtin.apt:
        name: tldr
        state: present

    - name: Install exa - like ls but better
      ansible.builtin.apt:
        name: exa
        state: present

    - name: Install ncdu
      ansible.builtin.apt:
        name: ncdu
        state: present

    - name: Install duf - like df but better
      ansible.builtin.apt:
        name: duf
        state: present

    - name: Install jq
      ansible.builtin.apt:
        name: jq
        state: present

    - name: Install speedtest-cli
      ansible.builtin.apt:
        name: speedtest-cli
        state: present

    - name: Install libavfilter-dev
      ansible.builtin.apt:
        name: libavfilter-dev
        state: present

    - name: Install iotop
      ansible.builtin.apt:
        name: iotop
        state: present
