---
- name: Set GCC auto
  hosts: all
  vars_files:
    - sudo.yml
  gather_facts: yes
  become: yes
  tasks:
    - name: Set auto mode for alternatives
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - update-alternatives --auto g++
        - update-alternatives --auto gcc
        - update-alternatives --auto cpp-bin
