---
- name: Set up lllm environment
  hosts: all
  become: no
  vars_files:
    - sudo.yml
  tasks:
    - name: Install ffmpeg
      become: yes
      ansible.builtin.apt:
        name: ffmpeg
        state: present

    - name: Install libmimalloc2.0
      become: yes
      ansible.builtin.apt:
        name: libmimalloc2.0
        state: present

    - name: Install gcc-11
      become: yes
      ansible.builtin.apt:
        name: gcc-11
        state: present

    - name: Install g++-11
      become: yes
      ansible.builtin.apt:
        name: g++-11
        state: present

    - name: Set auto mode for alternatives
      become: yes
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - update-alternatives --set g++ /usr/bin/g++-11
        - update-alternatives --set gcc /usr/bin/gcc-11
        - update-alternatives --set cpp-bin /usr/bin/cpp-11

    - name: Install pdsh
      become: yes
      ansible.builtin.apt:
        name: pdsh
        state: present

    - name: Install OpenMPI library
      become: yes
      ansible.builtin.apt:
        name: libopenmpi-dev
        state: present

    - name: Install libaio-dev library
      become: yes
      ansible.builtin.apt:
        name: libaio-dev
        state: present

    - name: Install ninja-build library
      become: yes
      ansible.builtin.apt:
        name: ninja-build
        state: present

    - name: Check if lllm repository exists
      ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/sources/lllm"
      register: lllm_repository

    - name: Add github.com to known_hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        state: present
        path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

    - name: Clone lllm repository
      ansible.builtin.git:
        repo: git@github.com:catid/lllm
        dest: "{{ lookup('env', 'HOME') }}/sources/lllm"
        update: "{{ lllm_repository.stat.exists }}"

    - name: Check if lllm conda environment exists
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'HOME') }}/mambaforge/bin/conda env list | grep lllm"
      register: conda_env_output
      ignore_errors: true

    - name: Create lllm conda environment and install dependencies
      block:
        - name: Create conda environment
          ansible.builtin.shell:
            cmd: "{{ lookup('env', 'HOME') }}/mambaforge/bin/conda create -y --name lllm python=3.8"
      when: conda_env_output.rc != 0

    - name: Install pip requirements.txt
      shell: |
        cd "{{ lookup('env', 'HOME') }}/sources/lllm"
        "{{ lookup('env', 'HOME') }}/mambaforge/envs/lllm/bin/pip" install -r requirements.txt
