---
- name: Update upsampling repository
  hosts: all
  vars_files:
    - sudo.yml
  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
      become: yes

    - name: Git pull on ~/sources/upsampling
      ansible.builtin.git:
        repo: git@github.com:catid/upsampling.git
        dest: "{{ lookup('env', 'HOME') }}/sources/upsampling"
        update: yes
        accept_hostkey: yes

    - name: Install PyTorch, torchvision, and functorch
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'HOME') }}/mambaforge/envs/upsampling/bin/pip install --extra-index-url https://download.pytorch.org/whl/cu118 --upgrade torch torchvision functorch"

    - name: Install NVIDIA DALI
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'HOME') }}/mambaforge/envs/upsampling/bin/pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110"

    - name: Update pip with any newly added requirements
      shell: |
        cd "{{ lookup('env', 'HOME') }}/sources/upsampling"
        "{{ lookup('env', 'HOME') }}/mambaforge/envs/upsampling/bin/pip" install --upgrade -r requirements.txt
