---
- name: Update upsampling repository
  hosts: all
  gather_facts: no
  vars_files:
    - sudo.yml
  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
      become: yes

    - name: Git pull on ~/sources/upsampling
      ansible.builtin.git:
        repo: git@github.com:catid/upsampling.git
        dest: "~/sources/upsampling"
        update: yes
        accept_hostkey: yes

    - name: Install requirements from requirements.txt
      ansible.builtin.pip:
        requirements: "{{ lookup('env', 'HOME') }}/sources/upsampling/requirements.txt"
        virtualenv: "{{ lookup('env', 'HOME') }}/miniconda3/envs/upsampling"
