---
- name: Update lllm repository
  hosts: all
  vars_files:
    - sudo.yml
    - hftoken.yml
  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
      become: yes

    - name: Git pull on ~/sources/lllm
      ansible.builtin.git:
        repo: git@github.com:catid/lllm.git
        dest: "{{ lookup('env', 'HOME') }}/sources/lllm"
        update: yes
        accept_hostkey: yes

    - name: Update pip with any newly added requirements
      shell: |
        cd "{{ lookup('env', 'HOME') }}/sources/lllm"
        "{{ lookup('env', 'HOME') }}/mambaforge/envs/lllm/bin/pip" install --upgrade -r requirements.txt

    - name: Install HuggingFace token
      shell: |
        cd "{{ lookup('env', 'HOME') }}/sources/lllm"
        "{{ lookup('env', 'HOME') }}/mambaforge/envs/lllm/bin/huggingface-cli" login --token {{ hftoken }}
